### ISSUE TITLE
Reset rows selection when changing databases and/or experiment names

### ISSUE THREAD

**Issue by TomVeniat** [VincSP/Dash-Vision#6]
When switching databases or adding/removing experiment names, the datatable is updated but the selected rows are kept.
We should instead reset the selection or keep the selection of the rows that remains in the table after the update (but based on their ìd` and not on their position in the table as currently done).

**Comment by VincSP** [comment]
To deselect row, i choose to  clear the list attribute  'selected_rows' of the data table by this way : 

`@app.callback(Output('experiment-table', 'selected_rows'),
              [Input('update-selected-runs', 'n_clicks')],
              [State('experiment-table', 'selected_rows')])
def reset_selected_rows(value, selected_rows ):
    time.sleep(0.1)
    selected_rows[:] = []
    return selected_rows`

I did put a time.sleep(0.1) because the attribute 'selected_rows' is used  previously in an other callback :  
`@app.callback(Output('tab-data', 'data'),
              [Input('tab-content', 'children'),
               Input('update-selected-runs', 'n_clicks')],
              [State('database-selector', 'value'),
               State('experiment-table', 'selected_rows'),
               State('experiment-table', 'data')])
def populate_hidden(tab, update_clicks, db_name, selected_rows, table_data):
    if db_name is None:
        logger.warning('No database selected')
        raise PreventUpdate

    selected_ids = sorted([table_data[i]['_id'] for i in selected_rows])
    return {
        'db': db_name,
        'selected_ids': selected_ids,
    }
`
which populate the hidden datatble. And if we don't wait, the previous callback will not get his job done cause selected_rows is cleared by next callback.

Moreover, the data is cleared when you're switching tabs. I will look for other solutions

**Comment by VincSP** [comment]
Finally, 
```
@app.callback(Output('experiment-table', 'selected_rows'),
              [Input('add-query', 'n_submit'),
               Input('add-column', 'n_submit'),
               Input('experiment-selector', 'value'),
               Input('database-selector', 'value')],
              [State('experiment-table', 'selected_rows')])
def reset_selected_rows(v_submit,n_submit,value_experiment, value_database, selected_rows ):
    selected_rows[:] = []
    return selected_rows
```
